title: Title Demo
email: gukkos@gmail.com
description: >
  This site is a static blog on Jekyll and GitHub Pages
baseurl: ""
url: "http://www.gukow.com"
github_username: gukoff
markdown: kramdown
author:
  name: "Konstantin Gukov"
  email: gukkos@gmail.com
encoding: utf-8
timezone: Asia/Yekaterinburg
permalink: :year/:month/:day/:title.html
exclude:
  - README.md
  - Gemfile.lock
  - Gemfile
  - Rakefile
  - LICENSE.txt

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

paginate: 8
paginate_path: "p/:num"
excerpt_separator: <!--more-->

feed:
  title: gukow.com
  subtitle: Subtitle Demo
  path: rss.xml

sass:
  style: compressed
  deploy_style: compressed
  compile_in_place: false
